spring:
  profiles:
    group:
      local:
        - "verbose"
        - "flyway-dev"
        - "no-management"
      compose:
        - "verbose"
        - "db"
        - "flyway-dev"
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${LOGGING_EXPORT_ENDPOINT:http://localhost:4318/v1/logs}
    tracing:
      export:
        otlp:
          endpoint: ${TRACING_EXPORT_ENDPOINT:http://localhost:4318/v1/traces}
    otlp:
      metrics:
        export:
          url: ${METRICS_EXPORT_ENDPOINT:http://localhost:4318/v1/metrics}
