spring:
  profiles:
    group:
      local:
        - "verbose"
        - "flyway-dev"
      compose:
        - "verbose"
        - "db"
        - "flyway-dev"
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: when_authorized
